### ISSUE TITLE
variables wrong

### ISSUE THREAD

**Issue by qptrello** [minchingtonak/vw#1]
vw/caddy/Caddyfile 
${DOMAIN_PATH}
The variables in this file will cause an error
I deleted it and everything is fine, thanks for your work

**Comment by minchingtonak** [comment]
Hi! Thanks for submitting an issue. To be honest, I created this project very recently so I didn't expect anyone to start using it so soon 😅. I'm still actively working on new features and thought it would be ok to have breaking changes on `main` since nobody else was using it, but that's obviously not the case anymore. Moving forward, I'll make sure that the main branch doesn't contain any WIP/broken features. I'll go ahead and remove the `DOMAIN_PATH` stuff for now and work on it on a feature branch.

**Comment by minchingtonak** [comment]
Fix was just pushed, let me know if there are anymore issues.
